### ISSUE TITLE
Update on App Extension Support

### ISSUE THREAD

**Issue by ApolloZhu** [LiulietLee/LLDialog#10]
https://github.com/LiulietLee/LLDialog/blob/b2dfa42b8c899eccfdff857769e260186bcabed0/Source/LLDialog.swift#L75

We used to do this because of [SR-1226](https://bugs.swift.org/browse/SR-1226), but since https://github.com/apple/swift/pull/12410 got merged, there's no need for `#keyPath`. Suggested change: 

```swift
let keyWindow = UIApplication.shared.keyWindow
```

**Comment by LiulietLee** [comment]
(￣▽￣)~*
