### ISSUE TITLE
UIApplication.shared() is not available in extensions

### ISSUE THREAD

**Issue by ApolloZhu** [LiulietLee/LLDialog#5]
# Situation

When I tried to add `LLDialog` to my iMessages Extension, the compiler says:
`'shared()' is unavailable: Use view controller based solutions where appropriate instead.`
# Questions
1. How can we solve this problem? (Or we are not going to support extensions?)
2. Do we need a new branch for swift 3.0?

**Comment by LiulietLee** [comment]
I haven't developed extensions so I also don't know how to solve this... I'm learning networking currently.

p.s. 额。。。因为我马上就要高三了，也没多少时间来搞swift了，所以你以后如果有什么pull request的话可以给我发个私信提醒我一下。

**Comment by ApolloZhu** [comment]
I may come up with some solutions later
不着急，有空再说，我暂时估计也不会有多大动静，暑假要学 java, c# 和 visual basic 为明年上课做准备
加油，网络我自己没肯动，到时候有问题可能要请教你
