### ISSUE TITLE
Provide Podspec

### ISSUE THREAD

**Issue by elsesiy** [LiulietLee/LLDialog#8]
Hey there,

can you create a Podspec for this repo so people don't need to manually copy the file into their projects?

This would allow proper versioning and cleaner dependency management.
I can assist you with that 👍 

Cheers!

**Comment by ApolloZhu** [comment]
Could you please also add Carthage and Swift Package Manager support?

**Comment by elsesiy** [comment]
SPM won't work because the view relies on UIKit which is afaik still not supported by it, but Carthage shouldn't be a Problem.

**Comment by LiulietLee** [comment]
OK but I have never used CocoaPod so I don't know how to create Podspec.
